apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: server
          image: antondeswardt/docker-complex-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-clusterip
            - name: REDIS_PORT
              value: "6379"
            - name: PGHOST
              value: postgres-clusterip
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            # need to add encrypted PGPASSWORD
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD